version: "3.8"
services:
  pgadmin4:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    environment:
      - PGADMIN_DEFAULT_EMAIL=your_email@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=1205
    ports:
      - "89:80"
    networks:
      - postgres-network
  postgres:
    image: postgres:10
    container_name: postgres10_container
    environment:
      - POSTGRES_PASSWORD=1205
    ports:
      - "5432:5432"
    networks:
      - postgres-network
networks:
  postgres-network:
    driver: bridge